### ISSUE TITLE
setup.py looks for missing 'requirements.txt'

### ISSUE THREAD

**Issue by d2r** [ahmet2mir/exabgpctl#1]
```
∴ pip3 install exabgpctl
Collecting exabgpctl
  Downloading https://files.pythonhosted.org/packages/1f/73/0302ff5e23ad76e5a661895d32cc0aa41c81679ef84746b3ee6565cea505/exabgpctl-19.1.post2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tj/3460qnm55s768v5tmyl5fn6r0000gp/T/pip-install-4ynlpb92/exabgpctl/setup.py", line 39, in <module>
        install_requires=open("requirements.txt").read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tj/3460qnm55s768v5tmyl5fn6r0000gp/T/pip-install-4ynlpb92/exabgpctl/
```

It seems [requirements.txt](https://github.com/ahmet2mir/exabgpctl/blob/93b4e6f2d6e6103eec9401ed0bdbb84ba30c828e/requirements.txt) is referenced from [setup.py](https://github.com/ahmet2mir/exabgpctl/blob/93b4e6f2d6e6103eec9401ed0bdbb84ba30c828e/setup.py#L39) but does not seem to be present in the `tar.gz` that is provided via [PyPi](https://pypi.org/project/exabgpctl/).

If the `requirements.txt` file is downloaded and `setup.py` is run directly, it seems to work.

**Comment by ahmet2mir** [comment]
Hello @d2r ,

Thanks for reporting this. I added the missing MANIFEST.in file,
now must works with version 19.06-1.

https://travis-ci.org/ahmet2mir/exabgpctl/builds/546795636

Don't hesitate to create new issues or features :)

**Comment by d2r** [comment]
Thank you @ahmet2mir for your prompt attention! I waited for the Travis build to complete and can confirm just now that it seems to install properly.
